import ProjectDescription

let nameAttribute: Template.Attribute = .required("name")

let exampleContents =
    """
    // File automatically generated by tuist
    """

let testContents =
    """
    import Foundation
    import XCTest
    
    final class \(nameAttribute)Tests: XCTestCase {
    
        override func setUp() {
            super.setUp()
        }
    
        override func tearDown() {
            super.tearDown()
        }
    
        func test_example() {
            // Add your test here
        }
    }
    """

let rootPath = "Github-GraphQL-Browser/Feature"

let template = Template(
    description: "Feature-framework template",
    attributes: [
        nameAttribute,
        .optional("platform", default: "iOS"),
    ],
    items: [
        .file(path: "\(rootPath)/\(nameAttribute)/Project.swift", templatePath: "../stencil/feature_project.stencil"),
        // Sources
        .file(
            path: "\(rootPath)/\(nameAttribute)/Sources/\(nameAttribute)Builder.swift",
            templatePath: "../stencil/CleanSwift/builder.stencil"),
        .file(
            path: "\(rootPath)/\(nameAttribute)/Sources/\(nameAttribute)Interactor.swift",
            templatePath: "../stencil/CleanSwift/interactor.stencil"),
        .file(
            path: "\(rootPath)/\(nameAttribute)/Sources/\(nameAttribute)Presenter.swift",
            templatePath: "../stencil/CleanSwift/presenter.stencil"),
        .file(
            path: "\(rootPath)/\(nameAttribute)/Sources/\(nameAttribute)ViewController.swift",
            templatePath: "../stencil/CleanSwift/viewController.stencil"),
        // Mock
        .string(path: "\(rootPath)/\(nameAttribute)/Mocks/\(nameAttribute)Mock.swift", contents: exampleContents),
        // Example
        .file(path: "\(rootPath)/\(nameAttribute)/Example/\(nameAttribute)AppDelegate.swift", templatePath: "../stencil/example_app_delegate.stencil"),
        .file(path: "\(rootPath)/\(nameAttribute)/Example/LaunchScreen.xib", templatePath: "../stencil/launch_screen.stencil"),
        .string(path: "\(rootPath)/\(nameAttribute)/Tests/\(nameAttribute)Tests.swift", contents: testContents),
        .string(path: "\(rootPath)/\(nameAttribute)/UITests/\(nameAttribute)UITests.swift", contents: testContents),
    ])
