disabled_rules:
   - trailing_whitespace
   - void_return
   - multiple_closures_with_trailing_closure
   - trailing_comma
   - nesting
   - trailing_newline

opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - convenience_type
  - cyclomatic_complexity
  - discouraged_object_literal
  - empty_string
  - redundant_string_enum_value
  - toggle_bool
  - uiimage
  - uistoryboard
  - uinib
  - uistoryboardsegue

excluded:
  - ./**/*.generated.swift
  - ./**/API.swift
  
function_body_length:
  warning: 60
  error: 70
  
type_name:
  min_length: 4
  max_length:
    warning: 50
    error: 60
  
line_length:
  warning: 130
  error: 160

identifier_name:
  excluded:
    - id

custom_rules:
  uiimage:
      included: ".*.swift"
      name: "UIImage Hardcoded"
      regex: UIImage\(named:\ ?\"(.*)\"\)
      message: "Hardcoded UIImage strings are not allowed."
      severity: error
  uistoryboard:
    included: ".*.swift"
    name: "UIStoryboard Hardcoded"
    regex: UIStoryboard\(name:\ ?\"(.*)\"\)
    message: "Hardcoded UIStoryboard strings are not allowed."
    severity: error
  uinib:
    included: ".*.swift"
    name: "UINib Hardcoded"
    regex: \(nibName:\ ?\"(.*)\"\)
    message: "Hardcoded UINib strings are not allowed."
    severity: error
  uistoryboardsegue:
    included: ".*.swift"
    name: "UIStoryboardSegue Hardcoded"
    regex: performSegue\(withIdentifier:\ ?\"(.*)\"\)
    message: "Hardcoded UIStoryboardSegue strings are not allowed."
    severity: error
