import ProjectDescription

let nameAttribute: Template.Attribute = .required("name")

let exampleContents =
    """
    // File automatically generated by tuist
    """

let testContents =
    """
    import Foundation
    import XCTest
    
    final class \(nameAttribute)Tests: XCTestCase {
    
        override func setUp() {
            super.setUp()
        }
    
        override func tearDown() {
            super.tearDown()
        }
    
        func test_example() {
            // Add your test here
        }
    }
    """

let rootPath = "Github-GraphQL-Browser/Foundation"

let template = Template(
    description: "Feature-framework template",
    attributes: [
        nameAttribute,
        .optional("platform", default: "iOS"),
    ],
    items: [
        .string(path: "\(rootPath)/\(nameAttribute)/Sources/\(nameAttribute).swift", contents: exampleContents),
        .string(path: "\(rootPath)/\(nameAttribute)/Tests/\(nameAttribute)Tests.swift", contents: testContents),
        .string(path: "\(rootPath)/\(nameAttribute)/Mocks/\(nameAttribute)Mock.swift", contents: exampleContents),
        .file(path: "\(rootPath)/\(nameAttribute)/Project.swift", templatePath: "../stencil/foundation_project.stencil"),
    ])
